name: asset compress

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: compress
        uses: ongyjho/JSCSSCompressor@master
        